---
title       : Get Your Certificate of Distinction
subtitle    : Developing Data Products
author      : Courtney H.
job         : Student
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap,quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Learn What Grade You Need to Ace This Class!

Stressed to see if you can get that Certificate of Distinction for this class?
With FOUR easy steps, this app takes away the worry and let's you know what you need to get on the final project!

Run App Here: https://farkyster21.shinyapps.io/ShinyProject/

**As Easy as 1,2,3.....4**

1. Enter Your (%) Grade for the first Quiz in the first input box

2. Enter Your (%) Grade for the second Quiz in the second input box

3. Enter Your (%) Grade for the third Quiz in the third input box

4. PUSH READY!! 


--- .class #id 

## Need a little help with your % Grade Calculation?

Example: If you got 3 correct out of 5 possible questions on your first Quiz, your percent grade would be?

**Formula:**
(Number Correct/Number of Questions) * 100

```{r Grade, echo = TRUE}
(3/5)*100
```



Tadah!! You got 60% on your first quiz! Just enter that number into the first input box and continue these same steps for the remaining quizzes.

--- &radio

## Pop Quiz! Let's see if you got it!


Question 1

If there were 20 questions on the quiz and you got 15 right, what is your % grade on the quiz?

1. 20%

2. 15%

3. _75%_

4. 80%

*** .hint 
(Number Correct/Number of Questions) * 100

*** .explanation
(15/20)*100 = 75

--- .class #id 

## What Happens After you Press Ready?!?

Amazing-ness!

Just kidding.....kind of.

The right panel will first show you what you've initally entered, then below that it'll determine the grades you need on the project to pass with distinction. It will ouput one of the following:

1. Too Bad, Not Possible! :(

2. You're Amazing! You got it regardless!

3. [Your Actual Score]


**Easy as that! Thanks for listening, and good luck with the rest of the course!**

--- .class #id 